#!/bin/bash

REGION=cn
REGION=en

########################################
# set up macros
########################################
CDN_DIR=https://raw.githubusercontent.com/iebox/cdn/master/ide


CODE_DIR=~/Desktop/code
APP_DIR=/Applications

PY_PACK_URL=https://www.python.org/ftp/python/3.9.0/python-3.9.0-macosx10.9.pkg

if [ $REGION == cn ]; then
    CDN_DIR=https://py5u.com/cdn
    PY_PACK_URL=$CDN_DIR/py.pkg
fi

TAR_URL=$CDN_DIR/st_mac.tar.gz

########################################
# local save paths
########################################

PY_PACK_PATH=$CODE_DIR/.python.pkg
TAR_PATH=$CODE_DIR/.st.tar.gz

# printf '\e[1;40;92m'

APP_PATH=$APP_DIR/sublime_text.app
SUBL=$APP_PATH/Contents/SharedSupport/bin/subl

TESTFLIGHT_PATH=$CODE_DIR/testflight.py

TESTFLIGHT_URL=$CDN_DIR/testflight.py

clear
echo $TAR_URL
echo $PY_PACK_URL
echo $TESTFLIGHT_URL
# exit 0


# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/ 
# update python
# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/

mkdir -p $CODE_DIR


echo "Please input your cumputer login password: "
echo "just type and press Enter once done, password won't even show ******"
echo "If the application fails to open wait a bit and try again!"

sudo spctl --master-disable



# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/ 
echo "------ downloading sublime"
# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/

echo curl $TAR_URL -o $TAR_PATH
curl $TAR_URL -o $TAR_PATH


# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/ 
echo "------ unzip sublime"
# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/

echo tar zxvf $PWD/.pack/st.tar.gz -C $APP_DIR
tar zxvf $TAR_PATH -C $APP_DIR

if ! [ -d "$APP_PATH" ]; then
    echo sudo tar zxvf $TAR_PATH -C $APP_DIR
    sudo tar zxvf $TAR_PATH -C $APP_DIR
fi


# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/ 
echo "------ configure sublime"
# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/

xattr -r -d com.apple.quarantine $APP_PATH
sudo xattr -r -d com.apple.quarantine $APP_PATH
xattr -r -d com.apple.quarantine $APP_PATH


# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/ 
echo "------ downloading python"
# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/

# echo "print('hw')">$CODE_DIR/testflight.py
curl $PY_PACK_URL -o $PY_PACK_PATH


# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/ 
echo "------ install python"
# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/

echo sudo installer -allowUntrusted -verboseR -pkg $PY_PACK_PATH -target /
sudo installer -allowUntrusted -verboseR -pkg $PY_PACK_PATH -target /



# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/ 
echo "---------testing"
# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/


echo curl $TESTFLIGHT_URL -o $TESTFLIGHT_PATH
curl $TESTFLIGHT_URL -o $TESTFLIGHT_PATH
$SUBL $TESTFLIGHT_PATH


printf '\e[39m'
exit 0
