#!/bin/bash

printf '\e[1;40;92m'
clear

# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/ 
# set up macros
# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/

CODE_DIR=~/Desktop/code
APP_DIR=/Applications

PKG_URL=https://www.python.org/ftp/python/3.9.0/python-3.9.0-macosx10.9.pkg
PKG_PATH=$CODE_DIR/.python.pkg

TAR_URL=https://raw.githubusercontent.com/iebox/cdn/master/ide/st.tar.gz
TAR_PATH=$CODE_DIR/.st.tar.gz

APP_PATH=$APP_DIR/sublime_text.app
SUBL=$APP_PATH/Contents/SharedSupport/bin/subl

TESTFLIGHT_URL=https://raw.githubusercontent.com/iebox/cdn/master/ide/testflight.py
TESTFLIGHT_PATH=$CODE_DIR/testflight.py


# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/ 
# update python
# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/

mkdir -p $CODE_DIR


echo "Please input your cumputer login password: "
echo "just type and press Enter once done, password won't even show ******"
echo "If the application fails to open wait a bit and try again!"

sudo spctl --master-disable



# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/ 
echo "------ downloading sublime"
# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/

echo curl $TAR_URL -o $TAR_PATH
curl $TAR_URL -o $TAR_PATH


# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/ 
echo "------ unzip sublime"
# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/

echo tar zxvf $PWD/.pack/st.tar.gz -C $APP_DIR
tar zxvf $TAR_PATH -C $APP_DIR

if ! [ -d "$APP_PATH" ]; then
    echo sudo tar zxvf $TAR_PATH -C $APP_DIR
    sudo tar zxvf $TAR_PATH -C $APP_DIR
fi


# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/ 
echo "------ configure sublime"
# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/

xattr -r -d com.apple.quarantine $APP_PATH
sudo xattr -r -d com.apple.quarantine $APP_PATH
xattr -r -d com.apple.quarantine $APP_PATH


# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/ 
echo "------ downloading python"
# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/

# echo "print('hw')">$CODE_DIR/testflight.py
curl $PKG_URL -o $PKG_PATH


# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/ 
echo "------ install python"
# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/

echo sudo installer -allowUntrusted -verboseR -pkg $PKG_PATH -target /
sudo installer -allowUntrusted -verboseR -pkg $PKG_PATH -target /



# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/ 
echo "---------testing"
# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/


echo curl $TESTFLIGHT_URL -o $TESTFLIGHT_PATH
curl $TESTFLIGHT_URL -o $TESTFLIGHT_PATH
$SUBL $TESTFLIGHT_PATH


printf '\e[39m'
exit 0
